package io.virbius.compiler;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import io.virbius.policy.BindScope;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.HexFormat;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/** Emits OpenResty nginx config + flattened effective JSON (compile-time path A). */
final class GatewayOpenrestyEmitter {

    private GatewayOpenrestyEmitter() {}

    static int emit(
            JsonNode root,
            Path gatewayDir,
            ObjectMapper json,
            String deployPrefix,
            VirbiusConfigMerger.DeployLayout layout)
            throws IOException {
        JsonNode gateway = gateway(root);
        JsonNode routes = gateway.path("routes");
        if (!routes.isArray() || routes.isEmpty()) {
            return 0;
        }

        String tenantId = root.path("tenant_id").asText("default");
        String bundleVersion = root.path("version").asText("0.1.0");

        Path openrestyDir = gatewayDir.resolve("openresty");
        Files.createDirectories(openrestyDir);

        GatewayApisixEmitter.emitSceneRegistry(root, gatewayDir, json);

        StringBuilder upstreams = new StringBuilder();
        upstreams.append("# generated by virbius-compiler; do not edit\n");
        StringBuilder locations = new StringBuilder();
        locations.append("# generated by virbius-compiler; do not edit\n");

        Map<String, JsonNode> upstreamById = new LinkedHashMap<>();
        ArrayNode manifestRoutes = json.createArrayNode();
        Set<String> emittedUris = new LinkedHashSet<>();
        int count = 0;
        String ollamaProxyEffectiveAbs = null;
        String ollamaProxyUpstreamId = null;
        JsonNode ollamaProxyUpstream = null;

        for (JsonNode route : routes) {
            String uri = route.path("uri").asText("/v1/chat/completions");
            if (!emittedUris.add(uri)) {
                continue;
            }
            String routeKey = VirbiusConfigMerger.routeKeyFromUri(uri);
            JsonNode upstream = VirbiusConfigMerger.resolveUpstream(root, route);
            String upstreamId = VirbiusConfigMerger.upstreamId(upstream, "virbius-upstream-" + routeKey);
            upstreamById.putIfAbsent(upstreamId, upstream);

            VirbiusConfigMerger.MergeResult merged =
                    VirbiusConfigMerger.mergeRoute(root, route, deployPrefix, tenantId, bundleVersion, layout);

            ObjectNode effectiveDoc = json.createObjectNode();
            effectiveDoc.put("schema_version", VirbiusConfigMerger.SCHEMA_VERSION);
            effectiveDoc.put("bundle_version", bundleVersion);
            effectiveDoc.put("tenant_id", tenantId);
            effectiveDoc.put("route_key", routeKey);
            effectiveDoc.put("uri", uri);
            effectiveDoc.put("upstream_id", upstreamId);
            ArrayNode methods = effectiveDoc.putArray("methods");
            appendMethods(route, methods);
            effectiveDoc.set("virbius", merged.effective());
            effectiveDoc.set("merge_trace", merged.mergeTrace());

            Path effectivePath = openrestyDir.resolve("effective-" + routeKey + ".json");
            json.writerWithDefaultPrettyPrinter().writeValue(effectivePath.toFile(), effectiveDoc);

            String effectiveAbs = effectivePath.toAbsolutePath().normalize().toString();
            locations.append(renderLocation(uri, effectiveAbs, routeKey, upstreamId, upstream));

            if (ollamaProxyEffectiveAbs == null) {
                ollamaProxyEffectiveAbs = effectiveAbs;
                ollamaProxyUpstreamId = upstreamId;
                ollamaProxyUpstream = upstream;
            }

            ObjectNode manifestRoute = json.createObjectNode();
            manifestRoute.put("route_key", routeKey);
            manifestRoute.put("uri", uri);
            manifestRoute.set("methods", methods);
            manifestRoute.put("effective_file", "openresty/effective-" + routeKey + ".json");
            manifestRoute.put("upstream_id", upstreamId);
            manifestRoute.put("checksum_sha256", sha256(Files.readString(effectivePath)));
            manifestRoutes.add(manifestRoute);
            count++;
        }

        for (Map.Entry<String, JsonNode> e : upstreamById.entrySet()) {
            upstreams.append(renderUpstream(e.getKey(), e.getValue()));
        }

        Files.writeString(openrestyDir.resolve("upstreams.conf"), upstreams.toString(), StandardCharsets.UTF_8);
        if (ollamaProxyEffectiveAbs != null) {
            locations.append(renderLocation(
                    "/api/chat",
                    ollamaProxyEffectiveAbs,
                    "api-chat",
                    ollamaProxyUpstreamId,
                    ollamaProxyUpstream));
        }
        Files.writeString(openrestyDir.resolve("locations.conf"), locations.toString(), StandardCharsets.UTF_8);

        ObjectNode manifest = json.createObjectNode();
        manifest.put("bundle_version", bundleVersion);
        manifest.put("tenant_id", tenantId);
        manifest.put("gateway", "openresty");
        manifest.set("routes", manifestRoutes);
        ObjectNode shared = manifest.putObject("shared_files");
        shared.put("scene_registry", "scene-registry-" + tenantId + ".json");
        shared.put("access_lists", tenantId + "-access-lists.json");
        json.writerWithDefaultPrettyPrinter().writeValue(openrestyDir.resolve("manifest.json").toFile(), manifest);

        return count;
    }

    private static JsonNode gateway(JsonNode root) {
        JsonNode gateway = root.get("gateway");
        if (gateway != null && !gateway.isMissingNode()) {
            return gateway;
        }
        return root.path("bundle").path("gateway");
    }

    private static void appendMethods(JsonNode route, ArrayNode methods) {
        JsonNode methodsNode = route.get("methods");
        if (methodsNode != null && methodsNode.isArray() && !methodsNode.isEmpty()) {
            methodsNode.forEach(m -> methods.add(m.asText()));
        } else {
            methods.add("POST");
        }
    }

    private static String renderUpstream(String id, JsonNode upstream) {
        StringBuilder sb = new StringBuilder();
        sb.append("upstream ").append(id).append(" {\n");
        List<String> nodes = parseNodes(upstream);
        if (nodes.isEmpty()) {
            sb.append("    server 127.0.0.1:11434 max_fails=3 fail_timeout=10s;\n");
        } else {
            for (String node : nodes) {
                sb.append("    server ").append(node).append(" max_fails=3 fail_timeout=10s;\n");
            }
        }
        sb.append("    keepalive 32;\n");
        sb.append("}\n\n");
        return sb.toString();
    }

    private static List<String> parseNodes(JsonNode upstream) {
        List<String> out = new ArrayList<>();
        if (upstream == null || upstream.isMissingNode()) {
            return out;
        }
        JsonNode nodes = upstream.get("nodes");
        if (nodes != null && nodes.isArray()) {
            for (JsonNode n : nodes) {
                String host = n.path("host").asText("");
                int port = n.path("port").asInt(0);
                if (!host.isBlank() && port > 0) {
                    out.add(host + ":" + port);
                }
            }
        } else if (nodes != null && nodes.isObject()) {
            nodes.fields()
                    .forEachRemaining(e -> out.add(e.getKey() + " weight=" + e.getValue().asText("1")));
        }
        return out;
    }

    private static String renderLocation(
            String uri, String effectiveAbs, String routeKey, String upstreamId, JsonNode upstream) {
        String accessLua = resolveAccessLuaPath();
        StringBuilder sb = new StringBuilder();
        sb.append(renderLocationDirective(uri));
        sb.append(" {\n");

        sb.append("    set $virbius_effective \"").append(effectiveAbs).append("\";\n\n");
        sb.append("    lua_need_request_body on;\n");
        sb.append("    client_body_in_single_buffer on;\n\n");
        sb.append("    access_by_lua_file ").append(accessLua).append(";\n\n");
        sb.append("    proxy_http_version 1.1;\n");
        sb.append("    proxy_set_header Connection \"\";\n");
        sb.append("    proxy_set_header Host ").append(resolveUpstreamHostHeader(upstream)).append(";\n");
        sb.append("    proxy_buffering off;\n");
        sb.append("    proxy_read_timeout 120s;\n");
        sb.append("    proxy_pass http://").append(upstreamId).append(";\n");
        sb.append("}\n\n");
        return sb.toString();
    }

    private static String resolveUpstreamHostHeader(JsonNode upstream) {
        List<String> nodes = parseNodes(upstream);
        if (nodes.isEmpty()) {
            return "127.0.0.1:11434";
        }
        String node = nodes.get(0);
        int weightIdx = node.indexOf(' ');
        if (weightIdx > 0) {
            node = node.substring(0, weightIdx);
        }
        return node;
    }

    static String renderLocationDirective(String uri) {
        BindScope.validateUriPattern(uri);
        if (uri.endsWith("*")) {
            String prefix = uri.substring(0, uri.length() - 1);
            return "location ^~ " + prefix;
        }
        if (uri.contains("*")) {
            throw new IllegalArgumentException("unsupported uri pattern for openresty location: " + uri);
        }
        return "location = " + uri;
    }

    private static String resolveAccessLuaPath() {
        String env = System.getenv("VIRBIUS_OPENRESTY_ACCESS_LUA");
        if (env != null && !env.isBlank()) {
            return env.trim();
        }
        return "/usr/local/virbius/plugins/openresty/access.lua";
    }

    private static String sha256(String content) {
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            byte[] hash = digest.digest(content.getBytes(StandardCharsets.UTF_8));
            return HexFormat.of().formatHex(hash);
        } catch (NoSuchAlgorithmException e) {
            throw new IllegalStateException(e);
        }
    }
}
